In [39]:
import pandas as pd

# 数据类型简介

## numpy 简介

In [1]:
import numpy as np

# 创建ndarray
score = np.array([
    [80, 89, 86, 67, 79],
    [78, 97, 89, 67, 81],
    [90, 94, 78, 67, 74],
    [91, 91, 90, 67, 69],
    [76, 87, 75, 67, 86],
    [70, 79, 84, 67, 84],
    [94, 92, 93, 67, 64],
    [86, 85, 83, 67, 80]
])

print(score)
print(type(score))

[[80 89 86 67 79]
 [78 97 89 67 81]
 [90 94 78 67 74]
 [91 91 90 67 69]
 [76 87 75 67 86]
 [70 79 84 67 84]
 [94 92 93 67 64]
 [86 85 83 67 80]]
<class 'numpy.ndarray'>


In [3]:
import random
import time
import numpy as np

a = []
for i in range(1000000):
    a.append(random.random())

t1 = time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t3=time.time()
sum2=np.sum(b)
t4=time.time()

print(t2-t1, t4-t3)

0.004060268402099609 0.0009953975677490234


## Numpy 的 ndarray

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [5]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 3)


In [6]:
c.ndim

3

In [7]:
c.size

12

In [8]:
c.itemsize

4

In [9]:
c.dtype

dtype('int32')

**创建ndarray并指定存储数据的类型**

## pandas 的数据类型

**加载seaborn模块内置的tips数据集**

# 数据类型转换

## astype函数：通用类型转换函数

## to_numeric 函数：指定类型转数值类型函数

# 分类数据类型

## category 类型转换

## 深入 category 数据类型

# 日期数据类型

## Python 的 datetime 对象

## to_datetime 函数

**加载country_timeseries.csv数据**

## 提取 datetime 的各个部分

## 日期运算和Timedelta

## date_range函数

**产生 2020-01-01 到 2020-01-07 的工作日**

**隔一个工作日取一个工作日**

**示例：2020年每个月的第一个星期四**

**示例：2020年每个月的第三个星期五**

## 日期序列数据操作

### DateTimeIndex 设置

**加载丹佛市报警记录数据集 crime.csv**

### 日期数据的筛选

**示例：获取 2016-05-02 的报警记录数据**

**示例：获取 2015-03-01 到 2015-06-01 之间的报警记录数据**

**示例：获取 2015-03-01 22点 到 2015-06-01 20:35:00 之间的报警记录数据**

**示例：查询凌晨两点到五点的报警记录**

**示例：查询在 5:47 分的报警记录**

### DateTimeIndex 行标签排序

**示例：获取 2015-03-04 到 2016-06-01 之间的报警记录数据**

### 日期序列数据的重采样

**示例：计算每周的报警数量**

**示例：分析每季度的犯罪和交通事故数量**