In [1]:
import pandas as pd

# 数据类型简介

## numpy 简介

In [14]:
import numpy as np

# 创建ndarray
score = np.array([
    [80, 89, 86, 67, 79],
    [78, 97, 89, 67, 81],
    [90, 94, 78, 67, 74],
    [91, 91, 90, 67, 69],
    [76, 87, 75, 67, 86],
    [70, 79, 84, 67, 84],
    [94, 92, 93, 67, 64],
    [86, 85, 83, 67, 80]
])

print(score)
print(type(score))

[[80 89 86 67 79]
 [78 97 89 67 81]
 [90 94 78 67 74]
 [91 91 90 67 69]
 [76 87 75 67 86]
 [70 79 84 67 84]
 [94 92 93 67 64]
 [86 85 83 67 80]]
<class 'numpy.ndarray'>


In [3]:
import random
import time
import numpy as np

a = []
for i in range(1000000):
    a.append(random.random())

t1 = time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t3=time.time()
sum2=np.sum(b)
t4=time.time()

print(t2-t1, t4-t3)

0.005759000778198242 0.0003361701965332031


## Numpy 的 ndarray

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [5]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 3)


In [6]:
c.ndim

3

In [7]:
c.size

12

In [8]:
c.itemsize

8

In [9]:
c.dtype

dtype('int64')

**创建ndarray并指定存储数据的类型**

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
b.dtype

dtype('float32')

## pandas 的数据类型

**加载seaborn模块内置的tips数据集**

In [1]:
import seaborn as sns
tips = sns.load_dataset('tips')
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

# 数据类型转换

## astype函数：通用类型转换函数

In [3]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
tips['sex_str'] = tips['sex'].astype(str)
print(tips.dtypes)

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
sex_str         object
dtype: object


In [5]:
tips

total_bill   tip     sex smoker   day    time  size sex_str
0         16.99  1.01  Female     No   Sun  Dinner     2  Female
1         10.34  1.66    Male     No   Sun  Dinner     3    Male
2         21.01  3.50    Male     No   Sun  Dinner     3    Male
3         23.68  3.31    Male     No   Sun  Dinner     2    Male
4         24.59  3.61  Female     No   Sun  Dinner     4  Female
..          ...   ...     ...    ...   ...     ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner     3    Male
240       27.18  2.00  Female    Yes   Sat  Dinner     2  Female
241       22.67  2.00    Male    Yes   Sat  Dinner     2    Male
242       17.82  1.75    Male     No   Sat  Dinner     2    Male
243       18.78  3.00  Female     No  Thur  Dinner     2  Female

[244 rows x 8 columns]

In [6]:
tips.head()

total_bill   tip     sex smoker  day    time  size sex_str
0       16.99  1.01  Female     No  Sun  Dinner     2  Female
1       10.34  1.66    Male     No  Sun  Dinner     3    Male
2       21.01  3.50    Male     No  Sun  Dinner     3    Male
3       23.68  3.31    Male     No  Sun  Dinner     2    Male
4       24.59  3.61  Female     No  Sun  Dinner     4  Female

## to_numeric 函数：指定类型转数值类型函数

In [7]:
tips['total_bill'] = tips['total_bill'].astype(str)
tips.dtypes

total_bill      object
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
sex_str         object
dtype: object

In [8]:
tips['total_bill'] = tips['total_bill'].astype(float)
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
sex_str         object
dtype: object

In [9]:
tips_sub_miss = tips.head(10)
tips_sub_miss.loc[[1, 3, 5, 7], 'total_bill'] = 'missing'
tips_sub_miss

/Users/zhengyuan.zhou/opt/anaconda3/envs/datasci/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


total_bill   tip     sex smoker  day    time  size sex_str
0      16.99  1.01  Female     No  Sun  Dinner     2  Female
1    missing  1.66    Male     No  Sun  Dinner     3    Male
2      21.01  3.50    Male     No  Sun  Dinner     3    Male
3    missing  3.31    Male     No  Sun  Dinner     2    Male
4      24.59  3.61  Female     No  Sun  Dinner     4  Female
5    missing  4.71    Male     No  Sun  Dinner     4    Male
6       8.77  2.00    Male     No  Sun  Dinner     2    Male
7    missing  3.12    Male     No  Sun  Dinner     4    Male
8      15.04  1.96    Male     No  Sun  Dinner     2    Male
9      14.78  3.23    Male     No  Sun  Dinner     2    Male

In [10]:
tips_sub_miss.dtypes

total_bill      object
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
sex_str         object
dtype: object

In [11]:
tips_sub_miss['total_bill'].astype(float)

ValueError: could not convert string to float: 'missing'

In [16]:
import pandas as pd

In [17]:
pd.to_numeric(tips_sub_miss['total_bill'])

ValueError: Unable to parse string "missing" at position 1

In [18]:
pd.to_numeric(tips_sub_miss['total_bill'], errors='coerce')

0    16.99
1      NaN
2    21.01
3      NaN
4    24.59
5      NaN
6     8.77
7      NaN
8    15.04
9    14.78
Name: total_bill, dtype: float64

In [19]:
pd.to_numeric(tips_sub_miss['total_bill'], errors='ignore')

0      16.99
1    missing
2      21.01
3    missing
4      24.59
5    missing
6       8.77
7    missing
8      15.04
9      14.78
Name: total_bill, dtype: object

In [21]:
# downcast参数设置为float之后, 
# total_bill的数据类型由float64变为float32
pd.to_numeric(tips_sub_miss['total_bill'], 
              errors='coerce', 
              downcast='float')

0    16.99
1      NaN
2    21.01
3      NaN
4    24.59
5      NaN
6     8.77
7      NaN
8    15.04
9    14.78
Name: total_bill, dtype: float32

# 分类数据类型

## category 类型转换

## 深入 category 数据类型

# 日期数据类型

## Python 的 datetime 对象

## to_datetime 函数

**加载country_timeseries.csv数据**

## 提取 datetime 的各个部分

## 日期运算和Timedelta

## date_range函数

**产生 2020-01-01 到 2020-01-07 的工作日**

**隔一个工作日取一个工作日**

**示例：2020年每个月的第一个星期四**

**示例：2020年每个月的第三个星期五**

## 日期序列数据操作

### DateTimeIndex 设置

**加载丹佛市报警记录数据集 crime.csv**

### 日期数据的筛选

**示例：获取 2016-05-02 的报警记录数据**

**示例：获取 2015-03-01 到 2015-06-01 之间的报警记录数据**

**示例：获取 2015-03-01 22点 到 2015-06-01 20:35:00 之间的报警记录数据**

**示例：查询凌晨两点到五点的报警记录**

**示例：查询在 5:47 分的报警记录**

### DateTimeIndex 行标签排序

**示例：获取 2015-03-04 到 2016-06-01 之间的报警记录数据**

### 日期序列数据的重采样

**示例：计算每周的报警数量**

**示例：分析每季度的犯罪和交通事故数量**